exclude: |
    (?x)^(
        docs/.*
    )$
repos:
  # Checks for debug statements and merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: debug-statements
      - id: check-merge-conflict
  # Pyupgrade: upgrades older python syntax to newer one
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    - id: pyupgrade
      args: ["--py38-plus"]
  # Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=79"]
  # Autoflake: removes unused imports and variables
  - repo: https://github.com/pycqa/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  # Manual Linting: Flake 8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
  # Static Type checking: MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        additional_dependencies:
        - types-pyyaml
        - types-filelock
        - types-setuptools
        entry: mypy

